language: node_js
node_js:
  - "6.12.0"
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

cache: yarn

before_script:
  - yarn global add bower
  - bower -v
  - bower i

script:
  - npm test
  - cat ./test/test.html
